### PR TITLE
decode into time.Time when interface{} provided

### PR DESCRIPTION
**Pull request by h12w**
time.Time should be decoded in this case rather than slice.

### CODE REVIEW

**Comment by vmihailenco** [comment]
This is backwards incompatible change so we can't make it in v2.

Also `0x92` is a code for array of 2 elements. Therefore we can't decode all such arrays as time.Time.

I think proper solution is to use https://golang.org/pkg/time/#Time.MarshalBinary and https://github.com/msgpack/msgpack/blob/master/spec.md#extension-type

**Comment by h12w** [comment]
I see. Do you think msgpack should assign a fixed extention type code to time.Time?

**Comment by vmihailenco** [comment]
>I see. Do you think msgpack should assign a fixed extention type code to time.Time?

It *can* do it, .e.g we can use id from "[-128, -1]: reserved for predefined types". Though we can only do it only in v3.

How urgently do you need this?

**Comment by h12w** [comment]
Not very urgent. I think I can come up with some workaround in the application side. (e.g. convert all slices of two integers to time and see if the time range is near enough to now)

The problem arises from the need to build a general tool to examine messages in a message queue without knowing its schema.

Even if time.Time can be extended with extended type code, the solution is not ideal, because it still lacks compatibility between different programming languages or even different msgpack implementations. I think it is necessary to define a standard binary representation of time in msgpack.

**Comment by vmihailenco** [comment]
>different programming languages or even different msgpack implementations

Yeah, but at least it should work if you control all sides and use extension type....

>a standard binary representation of time in msgpack

True, but this is unlikely to happen soon. And for Go we already have https://golang.org/pkg/time/#Time.MarshalBinary...

**Comment by h12w** [comment]
The representation of Time.MarshalBinary is an array of 15 bytes. It is not the same as what msgpack.v2 does. Do you plan to change to this format in msgpack.v3?

**Comment by vmihailenco** [comment]
If we decide to go with MarshalBinary then Python msgpack will need to understand such format too. Which is not very nice.

So far I think that the most portable way is to use extension code and Time.Format(time.RFC3339Nano). Probably msgpack spec should recommend some extension code for time...

**Comment by vmihailenco** [comment]
Ha, there is already a proposal https://github.com/msgpack/msgpack/pull/209

**Comment by h12w** [comment]
Great. Hope it enters the msgpack spec soon.

**Pull request closed without merging**
