### PR TITLE
golang to php  error

### PR DESCRIPTION
**Pull request by gyf19**
golang to php  error

### CODE REVIEW

**Comment by vmihailenco** [comment]
Hi,

What is the purpose of this change? Fixed names order? Performance?

**Comment by gyf19** [comment]
Fixed names order, if the order is not fixed,  php msgpack_unpack error

**Comment by gyf19** [comment]
can merged pull request ?

**Comment by vmihailenco** [comment]
@gyf19 I am very sorry - I forgot about this PR. Thanks for submitting.

**Comment by gyf19** [comment]
:+1:

**Pull request merged**
