### PR TITLE
Implement automatic loose interface decoding via SetLoose

### PR DESCRIPTION
**Pull request by viciious**
See issue #172

### CODE REVIEW

**Comment by vmihailenco** [comment]
This only fixes the issue for slices, but not for maps or structs. Can we add new option `dec := decode.NewDecoder(&buf).UseLoose(true/false)` (better name is welcome) and add internal helper like:

```
func (d *Decoder) decodeInterface() (interface{}, error) {
    if d.loose {
        return d.DecodeInterfaceLoose()
    }
    return d.DecodeInterface()
}
```

and use it whenever we decode into `interface{}`. What do you think?

**Comment by viciious** [comment]
Yeah, my implementation is more of a RFC than a proper solution. Another (possibly the cleanest option) would be introduction of a new loose decoder struct:
```
dec: = decode.NewLooseDecoder(&buf)
```

**Comment by vmihailenco** [comment]
I prefer option like `UseLoose` and `UseSomeOption`, because it allows you enable/disable/change whatever options you need. `NewLooseDecoder` implies that `loose` option is very special (requires different implementation) and can't be combined with other options (you can use `NewLooseDecoder` and `NewSometingDecoder` simultaneously), but I agree that name looks better.

**Comment by viciious** [comment]
I've decided to go with 'SetLoose' function name rather than 'UseLoose', which sounds more like an option name, rather than a function name and 'SetUseLoose' just sounds and looks too awkward.

**Comment by vmihailenco** [comment]
Thanks. I am going to rename `SetLoose` to `UseDecodeInterfaceLoose`, but otherwise all looks good.

**Pull request merged**
