### PR TITLE
make gopkg.in canonical to avoid downstream replace directives

### PR DESCRIPTION
**Pull request by lizthegrey**
Addresses problem with workaround for #266

### CODE REVIEW

**Comment by vmihailenco** [comment]
Go modules are available since Go 1.11 and now we are almost on Go 1.15. I think Go modules requirement is reasonable and people without Go modules should look for workarounds, not the other way round.

I am happy to improve Go modules support - not to replace Go module with something else. It is hard to predict what problem this change will cause for existing v4 users.

**Comment by lizthegrey** [comment]
Same problem with https://github.com/russross/blackfriday/issues/491 :(

**Comment by lizthegrey** [comment]
> Go modules are available since Go 1.11 and now we are almost on Go 1.15. I think Go modules requirement is reasonable and people without Go modules should look for workarounds, not the other way round.
> 
> I am happy to improve Go modules support - not to replace Go module with something else. It is hard to predict what problem this change will cause for existing v4 users.

This still uses Go modules, just changes the default import path so that Go module users & non-module users can all use the same path. But I can understand the reluctance to change the import path.

(ironically, the problem is that using gopkg.in paths with go1.12 _modules_ fails without this)

**Comment by vmihailenco** [comment]
Closing since v5 is stable for some time now.

**Pull request closed without merging**
