### PR TITLE
Add a utility function ExtType

### PR DESCRIPTION
**Pull request by h12w**
ExtType provides a fast way to extract the type field from an ext type without fully unmarshaling it

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can you please show this new function is supposed to be used?

**Comment by h12w** [comment]
We're optimizing our API and it turns out the fastest way is to write to a single binary journal file instead of database or other message queuing system. Each message in the journal file has different data types encoded with ext types, and then is processed by these consumers. Each consumer handles a specific type of message, so it is very useful to have a fast filter that can select a specific type of messages efficiently.

**Comment by vmihailenco** [comment]
Thanks, but that does not tell me much. E.g. I don't understand where do you get `value []byte` to be passed to `ExtType` function (AFAIK Decoder does not support reading bytes).

Anyway it looks like `ExtType` can be implemented in user space and has very limited usage. So I prefer to not adding it to the library until there is a well-defined use case.

Overall it sounds like the proper way to do it is to extend [PeekCode](https://godoc.org/gopkg.in/vmihailenco/msgpack.v2#Decoder.PeekCode) to return extension type:

```
code, extType, err := decoder.PeekCode()
```

or add new PeekExtCode API:

```
code, extType, err := decoder.PeekExtCode()
```

**Comment by h12w** [comment]
The binary journal has its own message framing format. It means that I can get each message value (encoded in MsgPack) one by one in the form of []byte, but I don't want to spend more CPU unmarshaling it unless I'm sure it is the exact type that this consumer handles. e.g.

```go
for scanner.Scan() {
    msg := scanner.Message()
    typ, err := codes.ExtType(msg.Value)
    if err != nil || typ != typXXX {
        continue
    }
    var v XXX
    if err := msgpack.Unmarshal(value, &v); err != nil {
    ......
}
```

The reason that I'd like this ExtType function in the msgpack.v2 package is that it contains internal knowlege about MsgPack specification, and I believe msgpack.v2 should contain the complete knowledge of MsgPack so that the application code does not have to handle the details.

**Comment by h12w** [comment]
Adding a PeekExtCode method seems reasonable, but it still introduces the overhead of NewDecoder, which contains newBufReader(r) and makeBuffer().

function ExtType might go into a utility subpackage like msgpack/mputil, or just stays in our own code as you said.

**Pull request closed without merging**
