### PR TITLE
Add extended types

### PR DESCRIPTION
**Pull request by dmcgowan**
Adds support for encoding and decoding extended types.  Also has support for encoding and decoding interfaces.

Still working on unit tests, but would appreciate a review on the design and layout

For use in https://github.com/docker/libchan

### CODE REVIEW

**Comment by dmcgowan** [comment]
Need to resolve a test failure after rebase

**Comment by vmihailenco** [comment]
This is very interesting PR that adds gob-like functionality, i.e. it preserves type info in the byte stream. But suggested API looks too low-level. I would expect only one addition:

```
// Register records a type, identified by a value for that type, under the provided id. That id will identify the concrete type of a value sent or received as an interface variable.
func Register(id int8, value interface{})
```

Suggested implementation is here: https://github.com/vmihailenco/msgpack/pull/24 . I wounder if it is enough for your needs.

PS Sorry for a long delay, but your PR is big and I did not have enough time during the week.

**Comment by dmcgowan** [comment]
Thanks for the reply.  It is a large PR and appreciate you taking the time to review it.  The API is a bit low level, mostly because I need encode based on interface matches as well as type matches.  For my implementation I also have the need of having the encoder/decoders bound to specific receiver instead of bound at the package level.  I realize what I am trying to do with libchan is not the normal use case so I will not be offended with a close or using the alternate implementation.  I would prefer to contribute as much as possible before forking the implementation.  Forking is likely inevitable given some other libchan-specific changes I need to make for partial encoding. If you want to work with me to provide the interfaces I need to not fork, I would love to do so. However your library is very well written and the interface is clean, I would hate to pollute that for changes that aren't usually needed.

I will review your extended type PR, see what I can use and hopefully contribute how I can.  Thanks!

**Comment by vmihailenco** [comment]
It would be very helpful if you can show some code demonstrating your use cases. Ideally it should be a test similar to https://github.com/vmihailenco/msgpack/blob/feature/ext/ext_test.go#L25 . I.e. show what you want to encode and what result do you expect when data is decoded.

**Comment by dmcgowan** [comment]
The unit tests included show what I need to be able do via interfaces. I need to be able to match interfaces and encode a value specific to that instance of the encoder. I needed to make an interface change to give me more flexibility with interfaces. Let's continue to try and converge ideas in your PR.  I am going to close this for now.

**Pull request closed without merging**
