### PR TITLE
Omit empty simple sturcts

### PR DESCRIPTION
**Pull request by mthjs**
Currently, we only omit default values for primitives, interfaces and,
pointers. This makes it difficult to determine if a primitive was
present in the unpacked message.

Whilst unpacking you can determine if a value is present by implementing
something similar to standard lib's database/sql.NullInt64 (or any of
the other Null* types), but then the "Valid" field will be included when
you marshal the struct.

To resovle this, we must check if the given struct is simple enough
(meaning it doesn't have any hidden fields) to compare to a
zero-initialized version of the struct. If it is simple enough, and the
provided struct is zero-initialized, and the struct is tagged with
"omitempty" we can exclude it from the resulting bytes.

### CODE REVIEW

**Comment by vmihailenco** [comment]
This is unusual (e.g. encoding/json does not do this) and backwards incompatible. Instead you could implement `IsZero` interface like this

```go
type NullInt struct {
	Valid bool
	Int   int
}

func (v *NullInt) IsZero() bool {
    return v.Valid
}
```

**Comment by mthjs** [comment]
after a quick grep, I couldn't find a place where IsZero is already used to determine if the value should be included in the resulting byte-slice after marshalling. Is your suggestion to not do the zero comparison on the struct but instead attempt to call IsZero to determine if the struct can be safely omitted?

**Comment by vmihailenco** [comment]
@mthjs looks like I've not ported the code from go-pg yet - https://github.com/go-pg/zerochecker/blob/master/zerochecker.go#L23-L25

**Comment by mthjs** [comment]
@vmihailenco thanks, I'll include something similar in this change-set

**Comment by mthjs** [comment]
I've changed it, types exposing `IsZero() bool` can now be excluded if their field has the `omitempty` tag.

**Comment by vmihailenco** [comment]
Thanks

**Pull request merged**
